server:
 port: 8081
 servlet:
  context-path: /user-management
springdoc:
 api-docs:
  path: /api-docs
spring:
 profiles:
  active: mem
---
spring:
 config:
  activate:
   on-profile: mem
 datasource:
  url: jdbc:h2:mem:userapp
  driverClassName: org.h2.Driver
  username: sa
  password: password
 jpa:
  generate-ddl: true
  database-platform: org.hibernate.dialect.HSQLDialect
  hibernate:
   ddl-auto: create-drop
---
spring:
 config:
  activate:
   on-profile: postgres
 datasource:
  url: jdbc:postgresql://localhost:5432/userapp
  username: postgres
  password: India@123
  driverClassName: org.postgresql.Driver
 jpa:
  hibernate:
   ddl-auto: create-drop
  generate-ddl: true